shell /usr/bin/zsh

enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no

tab_bar_style powerline
tab_bar_edge top
tab_powerline_style slanted
tab_title_template "{tab.active_oldest_exe}: {tab.active_oldest_wd}"

# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="Hack Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 9.0

# Shortcut fixes in neovim
map ctrl+shift+minus send_text all \x1f
map ctrl+shift+7 send_text all \x1f

map ctrl+shift+kp_subtract change_font_size all -1.0
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+kp_plus change_font_size all +1.0
map ctrl+shift+backspace change_font_size all 0

# Default
#: Increase font size

# map kitty_mod+equal  change_font_size all +2.0
# map kitty_mod+plus   change_font_size all +2.0
# map kitty_mod+kp_add change_font_size all +2.0
# map cmd+plus         change_font_size all +2.0
# map cmd+equal        change_font_size all +2.0
# map shift+cmd+equal  change_font_size all +2.0

#: Decrease font size

# map kitty_mod+minus       change_font_size all -2.0
# map kitty_mod+kp_subtract change_font_size all -2.0
# map cmd+minus             change_font_size all -2.0
# map shift+cmd+minus       change_font_size all -2.0

#: Reset font size

# map kitty_mod+backspace change_font_size all 0
# map cmd+0               change_font_size all 0
