background              #f0f1f4
foreground              #16161e
selection_background    #bfc9db
selection_foreground    #16161e
cursor                  #7aa2f7
cursor_text_color       #16161e

active_tab_background   #7aa2f7
active_tab_foreground   #16161e
inactive_tab_background #ccccee
inactive_tab_foreground #444444
active_border_color     #7aa2f7
inactive_border_color   #ccccee

## System colors
# normal
color0 #FCFCFC
color1 #D91010
color2 #1D9A16
color3 #BD5600
color4 #1261D1
color5 #C80D4B
color6 #00998E
color7 #777777

# bright
color8  #444444
color9  #E61717
color10 #28A745
color11 #d98b00
color12 #287DF5
color13 #FD1360
color14 #10B2A5
color15 #262626

## Color cube 6x6x6
# Override to get light orange
color16 #FF923A
# Override to get intense orange
color17 #FF7200
