background #1a1b26
foreground #c0caf5
selection_background #283457
selection_foreground #c0caf5
url_color #73daca
cursor #c0caf5
cursor_text_color #1a1b26

# Tabs
active_tab_background #7aa2f7
active_tab_foreground #16161e
inactive_tab_background #292e42
inactive_tab_foreground #545c7e
#tab_bar_background #15161e

# Windows
active_border_color #7aa2f7
inactive_border_color #292e42

# normal
color0 #262626
color1 #E61717
color2 #33DD2D
color3 #FF7200
color4 #287DF5
color5 #FD1360
color6 #17E6D6
color7 #AAAAAA

# bright
color8  #666666
color9  #E85454
color10 #5DE05B
color11 #FFBB00
color12 #598EF6
color13 #FD5378
color14 #54E8DA
color15 #FCFCFC

# extended colors
color16 #ff9e64
color17 #db4b4b
