shell zsh

enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no
notify_on_cmd_finish invisible 10.0

tab_bar_style powerline
tab_bar_edge top
tab_powerline_style slanted
tab_title_template "{custom}"

enabled_layouts tall:bias=60;full_size=1;mirrored=false,fat:bias=60;full_size=1;mirrored=false,stack
window_border_width 2pt
draw_minimal_borders no

cursor_trail 10
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 2

map kitty_mod+up next_window
map kitty_mod+down previous_window
map kitty_mod+s move_window_to_top
map kitty_mod+enter new_window_with_cwd
map kitty_mod+ä set_tab_title
map kitty_mod+# combine : first_window : toggle_layout stack

# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME
background_opacity 0.8
background_blur 64

# BEGIN_KITTY_FONTS
font_family      family="Hack Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 9.0

# neovim fixes
map ctrl+shift+minus send_text all \x1f
map ctrl+shift+7 send_text all \x1f
map ctrl+shift+kp_subtract change_font_size all -2.0
