background #ffffff
foreground #262626
selection_background #6fd2fc
selection_foreground #ffffff

cursor #6fd2fc

# Tabs
active_tab_background #7aa2f7
active_tab_foreground #16161e
inactive_tab_background #292e42
inactive_tab_foreground #888888
#tab_bar_background #15161e

# Windows
active_border_color #00ffff
inactive_border_color #888888

color0 #000000
color1 #f72729
color2 #32895c
color3 #f96f1c
color4 #125ccf
color5 #9f00bc
color6 #32c2c0
color7 #b2b2b2
color8 #545753
color9 #fb0416
color10 #2cc631
color11 #fcd627
color12 #156ffe
color13 #e800b0
color14 #39d5ce
color15 #ededec
