include kitty-linux.conf
font_size 11.0

# Default key
kitty_mod cmd+shift

# neovim fixes
map cmd+shift+minus send_text all \x1f
map cmd+shift+7 send_text all \x1f
map kitty_mod+home change_font_size all -2.0

map kitty_mod+m macos_cycle_through_os_windows

# Ctrl+Key fixes
map cmd+a send_key ctrl+a
map cmd+b send_key ctrl+b
map cmd+c send_key ctrl+c
map cmd+d send_key ctrl+d
map cmd+e send_key ctrl+e
map cmd+f send_key ctrl+f
map cmd+g send_key ctrl+g
map cmd+h send_key ctrl+h
map cmd+i send_key ctrl+i
map cmd+j send_key ctrl+j
map cmd+k send_key ctrl+k
map cmd+l send_key ctrl+l
map cmd+m send_key ctrl+m
map cmd+n send_key ctrl+n
map cmd+o send_key ctrl+o
map cmd+p send_key ctrl+p
map cmd+q send_key ctrl+q
map cmd+r send_key ctrl+r
map cmd+s send_key ctrl+s
map cmd+t send_key ctrl+t
map cmd+u send_key ctrl+u
map cmd+v send_key ctrl+v
map cmd+w send_key ctrl+w
map cmd+x send_key ctrl+x
map cmd+y send_key ctrl+y
map cmd+z send_key ctrl+z
map cmd+left  send_key ctrl+left
map cmd+right send_key ctrl+right
map cmd+backspace send_key ctrl+backspace
# To copy the mac native behaviour
map alt+backspace send_key ctrl+backspace
map alt+left      send_key ctrl+left
map alt+right     send_key ctrl+right
