$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        background: "#262626"
        foreground: "#287DF5"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: "{{ if .WSL }}WSL at {{ end }}{{ .Icon }} "
      - type: root
        background: "#262626"
        foreground: "#FD1360"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: "  "
      - type: session
        background: "#262626"
        foreground: "#8027D1"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: '{{ if eq .Env.OMP_SHOW_SESSION "1" }}{{ if .Root }}<b>{{ end }} {{ .UserName }}{{ if .Root }}</b>{{ end }}@{{ .HostName }} {{ end }}'
      - type: shell
        background: "#262626"
        foreground: "#FD1360"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: '{{ if ne .Name "zsh" }} {{ .Name }} {{ end }}'
        properties:
          mapped_shell_names:
            pwsh: ps
      - type: git
        properties:
          fetch_status: true
          fetch_upstream_icon: true
        background: "#262626"
        foreground: "#FFBB00"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: >-
          <> {{ .UpstreamIcon }}  {{ .HEAD }}{{
          if or .Ahead .Behind }} {{ end }}{{
          if .Ahead }}↑{{ .Ahead }}{{ end }}{{
          if .Behind }}↓{{ .Behind }}{{ end }}{{
          if .Staging.Changed }}<#5DE05B>  {{ .Staging.String }}</>{{ end }}{{
          if .Working.Changed }}<#FF8550>  {{ .Working.String }}</>{{ end }}{{
          if gt .StashCount 0 }}<#598EF6>  {{ .StashCount }}</>{{ end }} <>
      - type: python
        background: "#262626"
        foreground: "#33DD2D"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: "  {{ .Venv }} "
  - type: prompt
    alignment: right
    segments:
      - type: status
        background: "#262626"
        foreground: "#AB2044"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          status_template: "{{ reason .Code }}"
      - type: executiontime
        background: "#262626"
        foreground: "#AC7F1C"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          threshold: 500
          style: round
        template: " {{ .FormattedMs }}  "
      - type: time
        background: "#262626"
        foreground: "#2756A5"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          time_format: "15:04:05"
        template: " {{ .CurrentDate | date .Format }}  "
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        background: "#262626"
        foreground: "#287DF5"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          home_icon: "<#598EF6><b>~</b></>"
          right_format: "<#598EF6><b>%s</b></>"
          style: full
        template: " {{ .Path }} "
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: status
        foreground: "#33DD2D"
        foreground_templates:
          - "{{ if gt .Code 0 }}#E61717{{ end }}"
        style: plain
        properties:
          always_enabled: true
        template: "❯ "
version: 3
