$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - alignment: left
    type: prompt
    segments:
      - background: "#444444"
        foreground: "#EEEEEE"
        style: plain
        template: " {{ if .WSL }}WSL at {{ end }}{{.Icon}}  "
        type: os
      - background: "#444444"
        foreground: "#0087AF"
        style: plain
        template: "  "
        type: root
      - background: "#444444"
        foreground: "#5FD700"
        style: plain
        template: >-
          <#000000> </> {{ .UpstreamIcon }} {{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{
          .Staging.String }}</>{{ end }}{{ if and (.Working.Changed)
          (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{
          .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount
          }}{{ end }}
        type: git
        properties:
          fetch_status: true
          fetch_upstream_icon: true
      - background: transparent
        foreground: "#444444"
        style: plain
        template: ""
        type: text
  - alignment: right
    type: prompt
    segments:
      - background: "#444444"
        foreground: "#598587"
        leading_diamond: 
        style: diamond
        template: " {{ .UserName }}@{{ .HostName }} <#0087AF></> "
        type: session
      - background: "#444444"
        foreground: "#598587"
        properties:
          time_format: "15:04:05"
        style: plain
        template: " {{ .CurrentDate | date .Format }}   "
        type: time
  - alignment: left
    type: prompt
    newline: true
    segments:
      - background: "#444444"
        foreground: "#0087AF"
        properties:
          style: full
        style: plain
        template: " {{ .Path }} "
        type: path
      - background: transparent
        foreground: "#444444"
        style: plain
        template: 
        type: text
  - alignment: left
    type: prompt
    newline: true
    segments:
      - foreground: "#5DD101"
        foreground_templates:
          - "{{ if gt .Code 0 }}#FE0000{{ end }}"
        properties:
          always_enabled: true
        style: plain
        template: "❯ "
        type: status
version: 3
