$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        background: "#242424"
        foreground: "#3A86FF"
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        template: "{{ if .WSL }}WSL at {{ end }}{{ .Icon }} "
      - type: shell
        background: "#242424"
        foreground: "#F1184C"
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        template: '{{ if ne .Name "zsh" }} {{ .Name }} {{ end }}'
        properties:
          mapped_shell_names:
            pwsh: ps
      - type: root
        background: "#242424"
        foreground: "#F1184C"
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        template: "  "
      - type: git
        properties:
          fetch_status: true
          fetch_upstream_icon: true
        background: "#242424"
        foreground: "#FFBB00"
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        template: >-
          <> {{ .UpstreamIcon }}  {{ .HEAD }}{{
          if or .Ahead .Behind }} {{ end }}{{
          if .Ahead }}↑{{ .Ahead }}{{ end }}{{
          if .Behind }}↓{{ .Behind }}{{ end }}{{
          if .Staging.Changed }}<#44D1BE>  {{ .Staging.String }}</>{{ end }}{{
          if .Working.Changed }}<#FF966C>  {{ .Working.String }}</>{{ end }}{{
          if gt .StashCount 0 }}<#82AAFF>  {{ .StashCount }}</>{{ end }} <>
      - type: python
        background: "#242424"
        foreground: "#33DD2D"
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        template: "  {{ .Venv }} "
  - type: prompt
    alignment: right
    segments:
      - type: status
        background: "#242424"
        foreground: "#AC1C44"
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        properties:
          status_template: "{{ reason .Code }}"
      - type: executiontime
        background: "#242424"
        foreground: "#AC7F1C"
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        properties:
          threshold: 500
          style: round
        template: " {{ .FormattedMs }}  "
      - type: time
        background: "#242424"
        foreground: "#2F5CAC"
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        properties:
          time_format: "15:04:05"
        template: " {{ .CurrentDate | date .Format }}  "
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        background: "#242424"
        foreground: "#3A86FF"
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        properties:
          home_icon: "<#5A9CFF><b>~</b></>"
          right_format: "<#5A9CFF><b>%s</b></>"
          style: full
        template: " {{ .Path }} "
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: status
        foreground: "#5DD101"
        foreground_templates:
          - "{{ if gt .Code 0 }}#FE0000{{ end }}"
        style: plain
        properties:
          always_enabled: true
        template: "❯ "
version: 3
