$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        background: "0"
        foreground: "4"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: "{{ if .WSL }}WSL at {{ end }}{{ .Icon }} "
      - type: root
        background: "0"
        foreground: "5"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: "  "
      - type: session
        background: "0"
        foreground: "6"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: '{{ if eq .Env.OMP_SHOW_SESSION "1" }}{{ if .Root }}<b>{{ end }} {{ .UserName }}{{ if .Root }}</b>{{ end }}@{{ .HostName }} {{ end }}'
      - type: shell
        background: "0"
        foreground: "5"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: '{{ if ne .Name "zsh" }} {{ .Name }} {{ end }}'
        properties:
          mapped_shell_names:
            pwsh: ps
      - type: git
        properties:
          fetch_status: true
          fetch_upstream_icon: true
        background: "0"
        foreground: "11"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: >-
          <> {{ .UpstreamIcon }}  {{ .HEAD }}{{
          if or .Ahead .Behind }} {{ end }}{{
          if .Ahead }}↑{{ .Ahead }}{{ end }}{{
          if .Behind }}↓{{ .Behind }}{{ end }}{{
          if .Staging.Changed }}<10>  {{ .Staging.String }}</>{{ end }}{{
          if .Working.Changed }}<3>  {{ .Working.String }}</>{{ end }}{{
          if gt .StashCount 0 }}<12>  {{ .StashCount }}</>{{ end }} <>
      - type: python
        background: "0"
        foreground: "2"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: "  {{ .Venv }} "
      - type: text
        background: "0"
        foreground: "3"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: " {{ if .Env.OMP_CUSTOM1 }}{{ .Env.OMP_CUSTOM1 }}{{ end }} "
      - type: text
        background: "0"
        foreground: "14"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        template: " {{ if .Env.OMP_CUSTOM2 }}{{ .Env.OMP_CUSTOM2 }}{{ end }} "
  - type: prompt
    alignment: right
    segments:
      - type: status
        background: "0"
        foreground: "5"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          status_template: "{{ reason .Code }}"
      - type: executiontime
        background: "0"
        foreground: "11"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          threshold: 500
          style: round
        template: " {{ .FormattedMs }}  "
      - type: time
        background: "0"
        foreground: "4"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          time_format: "15:04:05"
        template: " {{ .CurrentDate | date .Format }}  "
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        background: "0"
        foreground: "4"
        style: diamond
        leading_diamond: 
        trailing_diamond: 
        properties:
          home_icon: "<12><b>~</b></>"
          right_format: "<12><b>%s</b></>"
          style: full
        template: " {{ .Path }} "
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: status
        foreground: "2"
        foreground_templates:
          - "{{ if gt .Code 0 }}1{{ end }}"
        style: plain
        properties:
          always_enabled: true
        template: "❯ "
version: 3
