$schema: >-
  https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - alignment: left
    type: prompt
    segments:
      - type: os
        background: "#242424"
        foreground: "#3A86FF"
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        template: " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
      - type: shell
        background: "#242424"
        foreground: "#F1184C"
        style: diamond
        leading_diamond: "<transparent,background></>"
        trailing_diamond: 
        template: '{{ if ne .Name "zsh" }} {{ .Name }} {{ end }}'
        properties:
          mapped_shell_names:
            pwsh: PS
      - type: root
        background: "#242424"
        foreground: "#F1184C"
        style: diamond
        leading_diamond: "<transparent,background></>"
        trailing_diamond: 
        template: "  "
      - type: git
        properties:
          fetch_status: true
          fetch_upstream_icon: true
        background: "#242424"
        foreground: "#FFBB00"
        style: diamond
        leading_diamond: "<transparent,background></>"
        trailing_diamond: 
        template: >-
          <> {{ .UpstreamIcon }}  {{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{
          .Staging.String }}</>{{ end }}{{ if and (.Working.Changed)
          (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{
          .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount
          }}{{ end }} <>
      - type: python
        background: "#242424"
        foreground: "#33DD2D"
        style: diamond
        leading_diamond: "<transparent,background></>"
        trailing_diamond: 
        template: "  {{ .Venv }} "
  - alignment: right
    type: prompt
    segments:
      - background: "#242424"
        foreground: "#3A86FF"
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        properties:
          time_format: "15:04:05"
        template: " {{ .CurrentDate | date .Format }}  "
        type: time
  - alignment: left
    type: prompt
    newline: true
    segments:
      - background: "#242424"
        foreground: "#3A86FF"
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        properties:
          style: full
        template: " {{ .Path }} "
        type: path
  - alignment: left
    type: prompt
    newline: true
    segments:
      - foreground: "#5DD101"
        foreground_templates:
          - "{{ if gt .Code 0 }}#FE0000{{ end }}"
        properties:
          always_enabled: true
        style: plain
        template: "❯ "
        type: status
version: 3
