require("searchjump"):setup({
	unmatch_fg = "#b2a496",
	match_str_fg = "#000000",
	match_str_bg = "#73AC3A",
	first_match_str_fg = "#000000",
	first_match_str_bg = "#73AC3A",
	label_fg = "#EADFC8",
	label_bg = "#BA603D",
	only_current = false,
	show_search_in_statusbar = false,
	auto_exit_when_unmatch = false,
	enable_capital_label = true,
	search_patterns = {},
	keys_label = {
		"a", "s", "d", "f", "g", "q", "w", "e", "r", "t", "y", "x", "c", "v", "b",
		"h", "j", "k", "l", "z", "u", "i", "o", "p", "n", "m",
		"A", "S", "D", "F", "G", "Q", "W", "E", "R", "T", "Y", "X", "C", "V", "B",
		"H", "J", "K", "L", "Z", "U", "I", "O", "P", "N", "M",
	},
})
