[mgr]
prepend_keymap = [
  { on = [ "c", "m" ], run = "plugin chmod",      desc = "Chmod on selected files" },
  { on = [ "M" ],      run = "plugin mount" ,     desc = "Load the disk mount plugin"},
  { on = [ "s" ],      run = "plugin searchjump", desc = "searchjump mode" },
  { on = [ "S", "f" ], run = "search --via=fd",   desc = "Search all files by name via fd" },
  { on = [ "S", "r" ], run = "search --via=rg",   desc = "Search all files by content via rg" },
  { on = [ "ö" ], run = "tab_switch -1 --relative",   desc = "Switch to the previous tab" },
  { on = [ "ä" ], run = "tab_switch 1 --relative",   desc = "Switch to the next tab" },
  { on = [ "q" ], run = "close",   desc = "Close current tab or quit if it's last" },
]
